---
- name: Check reboot required
  register: reboot_required_file
  become: yes
  stat:
    path: /var/run/reboot-required
    get_checksum: no

- name: Reboot required
  debug:
    msg: '{{ reboot_required_file }}'
  when: reboot_required_file.stat.exists

    #- name: Reboot if needed
    #  become: yes
    #  reboot:
    #    msg: "Reboot initiated by Ansible for kernel updates"
    #    connect_timeout: 5
    #    reboot_timeout: 300
    #    pre_reboot_delay: 0
    #    post_reboot_delay: 30
    #    test_command: uptime
    #  when: reboot_required_file.stat.exists
