---

- name: Randomize user password
  become: yes
  user:
    name: '{{ item.key }}'
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32 encrypt=sha512_crypt') }}"
  with_dict: '{{ accounts }}'
  register: usertest
