---

- name: Randomize user password
  become: yes
  user:
    name: '{{ item }}'
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32 encrypt=sha512_crypt') }}"
  loop: '{{ accounts_to_reset }}'
