---

- name: Install iptables-persistent
  vars:
    packages:
      present:
      - iptables-persistent
  include_role:
    name: install_packages

- name: Configure iptables save path
  set_fact:
    iptables_save_path: /etc/iptables/rules.v4

- name: Configure ip6tables save path
  set_fact:
    ip6tables_save_path: /etc/iptables/rules.v6

- name: Enable and start netfilter-persistent.service
  become: yes
  service:
    name: netfilter-persistent.service
    enabled: yes
    state: started
