---

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

- include_tasks: archlinux.yml
  when: ansible_facts['os_family'] == "Archlinux"

