---
- name: Create host directory in home directory
  become: no
  file:
    path: "{{ ansible_env.HOME }}/host"
    state: directory

- name: Mount the filesystem
  become: yes
  mount:
    path: "{{ ansible_env.HOME }}/host"
    src: main
    state: mounted
    fstype: 9p
    opts: trans=virtio,noauto,users
