---
- name: Create host directory in home directory
  become: yes
  file:
    path: "{{ ansible_env.HOME }}/host"
    state: directory
    mode: 0700
    owner: user
    group: user

- name: Mount the filesystem
  become: yes
  mount:
    path: "{{ ansible_env.HOME }}/host"
    src: main
    state: mounted
    fstype: 9p
    opts: trans=virtio,noauto,users
