---

- name: Remove first signin animation via registry
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableFirstLogonAnimation
    type: dword
    data: 0
