---

- name: Install dependencies
  vars:
    packages:
      present:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
  include_role:
    name: install_packages

- name: Install docker-ce
  vars:
    unofficial_repositories:
      docker:
        keys:
          - https://download.docker.com/linux/debian/gpg
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable
        packages:
          - docker-ce
  include_role:
    name: unofficial_repositories

- name: Enable docker service
  vars:
    services:
      docker: started
  include_role:
    name: services
