---
- name: Set authorized key from currently available public keys
  become: yes
  authorized_key:
    user: '{{ ssh_user }}'
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "~/.ssh/*.pub"
