---
- name: Restart sshd
  become: yes
  service:
    name: sshd
    state: restarted
  listen: 'restart_sshd'

- name: Restart sshguard
  become: yes
  service:
    name: sshguard
    state: restarted
  listen: 'restart_sshguard'

  #- name: Save iptables configuration
  #
  #- name: Autoload iptables configuration
