---
- name: Remove autologon default username
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    state: absent

- name: Remove autologon default password
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    state: absent

- name: Remove autologon AutoAdminLogon
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    state: absent
