---
- name: Install pwgen
  vars:
    packages:
      present:
      - pwgen
  include_role:
    name: install_packages

- name: Add tunnel users
  become: yes
  user:
    name: "{{ item }}"
    shell: /bin/false
  loop: "{{ tunnel_users }}"

- name: Configure sshd for the tunnel users
  become: yes
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User {{ item }}
        PasswordAuthentication yes
        MaxSessions 1 
        AllowTcpForwarding remote 
        X11Forwarding no 
        PermitTunnel no 
        GatewayPorts no 
        AllowAgentForwarding no 
        ForceCommand echo 'This account can only be used for port forwarding'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  notify: 'restart_sshd'
  loop: "{{ tunnel_users }}"

- name: Copy one-time password generation script
  become: yes
  copy:
    src: files/tunnel_one_time_password.sh
    dest: /usr/local/sbin/tunnel_one_time_password
    mode: 0750


- name: Copy Password generation script
  become: yes
  copy:
    src: files/random_password.sh
    dest: /usr/local/sbin/random_password
    mode: 0750
