---

- name: Set hostname
  become: yes
  ansible.builtin.hostname:
    name: "{{ newhostname }}"
  register: rename
  notify: reboot_needed

- name: Delete old ssh keys
  block:
    - name: List keys
      become: yes
      find:
        path: /etc/ssh/
        patterns: ssh_host_*key*
      register: keys
    - name: Delete
      become: yes
      file:
        state: absent
        path: "{{ item.path }}"
      when: regenerate_sshd_keys and rename.diff is defined
      loop: "{{ keys.files }}"

- name: Regenerate sshd keys for Debian-based
  become: yes
  shell: |
    dpkg-reconfigure openssh-server
  when: regenerate_sshd_keys and rename.diff is defined and ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"
  notify: 'restart_sshd'

- name: Update /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regex: '^127\.0\.0\.1'
    line: '127.0.0.1    {{ newhostname }}'
  when: rename.diff is defined
