---

- name: Get the current hostname
  become: no
  shell: |
    hostnamectl | awk '/hostname:/ {print $NF}'
  register: hostnamectl_oldhostname
  # Not needed, just to make ansible-lint happy :)
  changed_when: false

- set_fact:
    oldhostname: '{{ hostnamectl_oldhostname.stdout }}'

- name: Regenerate sshd keys
  become: yes
  shell: |
    rm /etc/ssh/ssh_host_*key*
    dpkg-reconfigure openssh-server
  when: regenerate_ssh_keys and oldhostname != newhostname and ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  when: regenerate_ssh_keys and oldhostname != newhostname and ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

- name: 'Change to {{ newhostname }}'
  become: yes
  shell: |
    hostnamectl set-hostname {{ newhostname }}
  when: oldhostname != newhostname
  notify: 'reboot_needed'

- name: Update /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regex: '^127\.0\.0\.1'
    line: '127.0.0.1    {{ newhostname }}'
