---
- name: Empty interfaces file
  become: yes
  copy:
    content: ""
    dest: /etc/network/interfaces

- name: Install NetworkManager
  vars:
    packages:
      present:
      - network-manager
  include_role:
    name: install_packages

- name: Enable NetworkManager
  vars:
    services:
      NetworkManager: started
  include_role:
    name: services
