---

- name: Select packages for Debian-based distros
  set_fact:
    local_packages:
      present:
        - lightdm
        - xfce4
        - xfce4-goodies
        - xorg
        - spice-vdagent
        - xserver-xorg-video-qxl
    local_services:
      lightdm: started
      spice-vdagent: started
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"


- name: Select packages for Arch-based distros
  set_fact:
    local_packages:
      present:
        - lightdm-gtk-greeter
        - lightdm-gtk-greeter-settings
        - spice-vdagent
        - ttf-droid
        - xfce4
        - xfce4-goodies
        - xorg
    local_services:
      lightdm: started
  when: ansible_facts['os_family'] == "Archlinux"


- name: Install XFCE
  vars:
    packages: "{{ local_packages }}"
  include_role:
    name: install_packages

- name: Start necessary services
  vars:
    services: "{{ local_services }}"
  include_role:
    name: services
