- name: 'Change to {{ newhostname }}'
  ansible.windows.win_hostname:
    # Remove the domain (if any)
    # For example will set the name "example" for "example.domain.tld"
    name: '{{  newhostname.split(".")[0] | lower }}'
  register: changename

- name: Reboot
  ansible.windows.win_reboot:
  when: changename.reboot_required
