---
- name: Add user accounts
  become: yes
  user:
    name: '{{ item.key }}'
    groups: '{{ item.value.groups }}'
    create_home: yes
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32 encrypt=sha512_crypt') }}"
    shell: '{{ account_shell }}'
    state: present
    update_password: on_create
    password_lock: "{{ password_lock }}"
  with_dict: '{{ accounts }}'

- name: Add authorized_keys
  become: yes
  authorized_key:
    user: '{{ item.key }}'
    state: present
    key: '{{ item.value.public_key }}'
  when: item.value != None
  with_dict: '{{ accounts }}'
