---
- name: Add docker
  include_role:
    name: docker

- name: Neo4J container
  become: yes
  vars:
    neo4j_password: "{{ lookup('password', 'credentials/neo4j_password chars=ascii_letters,digits length=32') }}"
  docker_container:
    name: neo4j
    image: neo4j
    state: started
    published_ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /neo4j/data:/data
    env:
      NEO4J_AUTH: 'neo4j/{{ neo4j_password }}'
