---

- name: Define Debian-based KVM packages
  set_fact:
    packages:
      present:
      - gir1.2-spiceclientgtk-3.0
      - dnsmasq
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - qemu-utils
      - spice-client-gtk
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"

- name: Define Arch-based KVM packages
  set_fact:
    packages:
      present:
        - bridge-utils
        - dnsmasq
        - libvirt
        - iptables-nft
        - qemu
        - virt-manager
        - virt-viewer
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install packages
  include_role:
    name: install_packages

- name: Configure DNS resolution
  block:
  - name: Enable dnsmasq resolution in NetworkManager
    become: yes
    ini_file:
      path: /etc/NetworkManager/conf.d/10-kvm-dns.conf
      create: yes
      mode: 0644
      section: main
      option: dns
      value: dnsmasq
    notify: 'reload_networkmanager'
  - name: Create dnsmasq network-specific config file
    file:
      path: /etc/NetworkManager/dnsmasq.d/libvirtd_dnsmasq.conf
      owner: root
      group: root
      mode: '0644'
  - name: Disable systemd-resolved
    become: yes
    service:
      name: systemd-resolved
      enabled: no
      state: stopped
  - name: Use dnsmasq for name resolution
    become: yes
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: nameserver 127.0.1.1
    when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Ubuntu"
