---
- name: Install Java and Firefox
  vars:
    packages:
      present:
        - default-jre
        - firefox-esr
        - xterm
  include_role:
    name: install_packages

- name: Copy burpsuite
  copy:
    src: ~/.burpsuite.jar
    dest: burp.jar

- name: Copy burpsuite license
  copy:
    src: ~/.burpsuite.license
    dest: burp.license

- name: Copy default user options
  copy:
    src: ~/.burpsuite.default_user_options.burp.json
    dest: default_user_options.burp.json

- name: Copy default project options
  copy:
    src: ~/.burpsuite.default_project_options.burp.json
    dest: default_project_options.burp.json
