---
- name: Install clamav
  vars:
    packages:
      present:
      - clamav
      - clamtk
  include_role:
    name: install_packages

- name: Enable OnAccess scanning
  become: yes
  lineinfile:
    path: /etc/clamav/clamd.conf
    line: '{{ item }}'
  loop:
    - OnAccessPrevention yes
    - OnAccessExcludeUname clamav
  notify: 'restart_clam_services'

- name: Log only on systemd journal
  become: yes
  block:
    - lineinfile:
        path: /etc/clamav/clamd.conf
        regexp: '^LogFile\s.*$'
        state: absent
    - lineinfile:
        path: /etc/clamav/freshclam.conf
        regexp: '^UpdateLogFile\s.*$'
        state: absent
  notify: 'restart_clam_services'

- name: Configure OnAccess scanning
  become: yes
  lineinfile:
    path: /etc/clamav/clamd.conf
    line: 'OnAccessIncludePath {{ item }}'
  loop: '{{ clamavonaccessdirs }}'
  notify: 'restart_clam_services'

- name: Copy systemd unit
  become: yes
  copy:
    remote_src: yes
    src: /usr/lib/systemd/system/clamav-clamonacc.service
    dest: /etc/systemd/system/clamav-clamonacc.service
    mode: 0755
    force: no

- name: Use fdpass
  become: yes
  lineinfile:
    path: /etc/systemd/system/clamav-clamonacc.service
    backrefs: yes
    regexp: '(^ExecStart=(?!.*?.--fdpass$).*)$'
    line: '\1 --fdpass'
  notify: 'restart_clam_services'

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - clamav-freshclam
    - clamav-clamonacc

