---
- name: Configure echo cancellation in pulseaudio
  become: yes
  blockinfile:
    path: /etc/pulse/default.pa
    state: absent
    block: |
      load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args="analog_gain_control=0\ digital_gain_control=1" source_name=echoCancel_source sink_name=echoCancel_sink
      set-default-source echoCancel_source
      set-default-sink echoCancel_sink
