---

- name: Enable multilib repository
  become: yes
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  register: addmultilib
  notify: 'update_pacman_cache'
