---

- name: Save iptables state
  become: yes
  community.general.iptables_state:
    ip_version: ipv4
    state: saved
    path: "{{ iptables_save_path }}"
  listen: 'save_ip4tables'

- name: Save ip6tables state
  become: yes
  community.general.iptables_state:
    ip_version: ipv6
    state: saved
    path: "{{ ip6tables_save_path }}"
  listen: 'save_ip6tables'

